### ISSUE TITLE
CSS Reset and Normalize

### ISSUE THREAD

**Issue by Safentis** [Xelsing/Next-template#3]
1. Надо добавить сброс стилей у элементов h1, h2, h(N)... p, ul, li, ol, a (все отступы и стандартные стили)
2. Следует добавить normalize правила
3. Следует убрать тестовую верстку и стили

**Comment by xelsing** [comment]
1. присутствует
2. не посчитал нужным, не нашел необходимые
3. удаляется при ините проекта по необходимости
